//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	policy "github.com/gocrane/crane-scheduler/pkg/plugins/apis/policy"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DynamicSchedulerPolicy)(nil), (*policy.DynamicSchedulerPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DynamicSchedulerPolicy_To_policy_DynamicSchedulerPolicy(a.(*DynamicSchedulerPolicy), b.(*policy.DynamicSchedulerPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*policy.DynamicSchedulerPolicy)(nil), (*DynamicSchedulerPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_policy_DynamicSchedulerPolicy_To_v1alpha1_DynamicSchedulerPolicy(a.(*policy.DynamicSchedulerPolicy), b.(*DynamicSchedulerPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HotValuePolicy)(nil), (*policy.HotValuePolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_HotValuePolicy_To_policy_HotValuePolicy(a.(*HotValuePolicy), b.(*policy.HotValuePolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*policy.HotValuePolicy)(nil), (*HotValuePolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_policy_HotValuePolicy_To_v1alpha1_HotValuePolicy(a.(*policy.HotValuePolicy), b.(*HotValuePolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PolicySpec)(nil), (*policy.PolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PolicySpec_To_policy_PolicySpec(a.(*PolicySpec), b.(*policy.PolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*policy.PolicySpec)(nil), (*PolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_policy_PolicySpec_To_v1alpha1_PolicySpec(a.(*policy.PolicySpec), b.(*PolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PredicatePolicy)(nil), (*policy.PredicatePolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PredicatePolicy_To_policy_PredicatePolicy(a.(*PredicatePolicy), b.(*policy.PredicatePolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*policy.PredicatePolicy)(nil), (*PredicatePolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_policy_PredicatePolicy_To_v1alpha1_PredicatePolicy(a.(*policy.PredicatePolicy), b.(*PredicatePolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PriorityPolicy)(nil), (*policy.PriorityPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PriorityPolicy_To_policy_PriorityPolicy(a.(*PriorityPolicy), b.(*policy.PriorityPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*policy.PriorityPolicy)(nil), (*PriorityPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_policy_PriorityPolicy_To_v1alpha1_PriorityPolicy(a.(*policy.PriorityPolicy), b.(*PriorityPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SyncPolicy)(nil), (*policy.SyncPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SyncPolicy_To_policy_SyncPolicy(a.(*SyncPolicy), b.(*policy.SyncPolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*policy.SyncPolicy)(nil), (*SyncPolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_policy_SyncPolicy_To_v1alpha1_SyncPolicy(a.(*policy.SyncPolicy), b.(*SyncPolicy), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_DynamicSchedulerPolicy_To_policy_DynamicSchedulerPolicy(in *DynamicSchedulerPolicy, out *policy.DynamicSchedulerPolicy, s conversion.Scope) error {
	if err := Convert_v1alpha1_PolicySpec_To_policy_PolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_DynamicSchedulerPolicy_To_policy_DynamicSchedulerPolicy is an autogenerated conversion function.
func Convert_v1alpha1_DynamicSchedulerPolicy_To_policy_DynamicSchedulerPolicy(in *DynamicSchedulerPolicy, out *policy.DynamicSchedulerPolicy, s conversion.Scope) error {
	return autoConvert_v1alpha1_DynamicSchedulerPolicy_To_policy_DynamicSchedulerPolicy(in, out, s)
}

func autoConvert_policy_DynamicSchedulerPolicy_To_v1alpha1_DynamicSchedulerPolicy(in *policy.DynamicSchedulerPolicy, out *DynamicSchedulerPolicy, s conversion.Scope) error {
	if err := Convert_policy_PolicySpec_To_v1alpha1_PolicySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_policy_DynamicSchedulerPolicy_To_v1alpha1_DynamicSchedulerPolicy is an autogenerated conversion function.
func Convert_policy_DynamicSchedulerPolicy_To_v1alpha1_DynamicSchedulerPolicy(in *policy.DynamicSchedulerPolicy, out *DynamicSchedulerPolicy, s conversion.Scope) error {
	return autoConvert_policy_DynamicSchedulerPolicy_To_v1alpha1_DynamicSchedulerPolicy(in, out, s)
}

func autoConvert_v1alpha1_HotValuePolicy_To_policy_HotValuePolicy(in *HotValuePolicy, out *policy.HotValuePolicy, s conversion.Scope) error {
	out.TimeRange = in.TimeRange
	out.Count = in.Count
	return nil
}

// Convert_v1alpha1_HotValuePolicy_To_policy_HotValuePolicy is an autogenerated conversion function.
func Convert_v1alpha1_HotValuePolicy_To_policy_HotValuePolicy(in *HotValuePolicy, out *policy.HotValuePolicy, s conversion.Scope) error {
	return autoConvert_v1alpha1_HotValuePolicy_To_policy_HotValuePolicy(in, out, s)
}

func autoConvert_policy_HotValuePolicy_To_v1alpha1_HotValuePolicy(in *policy.HotValuePolicy, out *HotValuePolicy, s conversion.Scope) error {
	out.TimeRange = in.TimeRange
	out.Count = in.Count
	return nil
}

// Convert_policy_HotValuePolicy_To_v1alpha1_HotValuePolicy is an autogenerated conversion function.
func Convert_policy_HotValuePolicy_To_v1alpha1_HotValuePolicy(in *policy.HotValuePolicy, out *HotValuePolicy, s conversion.Scope) error {
	return autoConvert_policy_HotValuePolicy_To_v1alpha1_HotValuePolicy(in, out, s)
}

func autoConvert_v1alpha1_PolicySpec_To_policy_PolicySpec(in *PolicySpec, out *policy.PolicySpec, s conversion.Scope) error {
	out.SyncPeriod = *(*[]policy.SyncPolicy)(unsafe.Pointer(&in.SyncPeriod))
	out.Predicate = *(*[]policy.PredicatePolicy)(unsafe.Pointer(&in.Predicate))
	out.Priority = *(*[]policy.PriorityPolicy)(unsafe.Pointer(&in.Priority))
	out.HotValue = *(*[]policy.HotValuePolicy)(unsafe.Pointer(&in.HotValue))
	return nil
}

// Convert_v1alpha1_PolicySpec_To_policy_PolicySpec is an autogenerated conversion function.
func Convert_v1alpha1_PolicySpec_To_policy_PolicySpec(in *PolicySpec, out *policy.PolicySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PolicySpec_To_policy_PolicySpec(in, out, s)
}

func autoConvert_policy_PolicySpec_To_v1alpha1_PolicySpec(in *policy.PolicySpec, out *PolicySpec, s conversion.Scope) error {
	out.SyncPeriod = *(*[]SyncPolicy)(unsafe.Pointer(&in.SyncPeriod))
	out.Predicate = *(*[]PredicatePolicy)(unsafe.Pointer(&in.Predicate))
	out.Priority = *(*[]PriorityPolicy)(unsafe.Pointer(&in.Priority))
	out.HotValue = *(*[]HotValuePolicy)(unsafe.Pointer(&in.HotValue))
	return nil
}

// Convert_policy_PolicySpec_To_v1alpha1_PolicySpec is an autogenerated conversion function.
func Convert_policy_PolicySpec_To_v1alpha1_PolicySpec(in *policy.PolicySpec, out *PolicySpec, s conversion.Scope) error {
	return autoConvert_policy_PolicySpec_To_v1alpha1_PolicySpec(in, out, s)
}

func autoConvert_v1alpha1_PredicatePolicy_To_policy_PredicatePolicy(in *PredicatePolicy, out *policy.PredicatePolicy, s conversion.Scope) error {
	out.Name = in.Name
	out.MaxLimitPecent = in.MaxLimitPecent
	return nil
}

// Convert_v1alpha1_PredicatePolicy_To_policy_PredicatePolicy is an autogenerated conversion function.
func Convert_v1alpha1_PredicatePolicy_To_policy_PredicatePolicy(in *PredicatePolicy, out *policy.PredicatePolicy, s conversion.Scope) error {
	return autoConvert_v1alpha1_PredicatePolicy_To_policy_PredicatePolicy(in, out, s)
}

func autoConvert_policy_PredicatePolicy_To_v1alpha1_PredicatePolicy(in *policy.PredicatePolicy, out *PredicatePolicy, s conversion.Scope) error {
	out.Name = in.Name
	out.MaxLimitPecent = in.MaxLimitPecent
	return nil
}

// Convert_policy_PredicatePolicy_To_v1alpha1_PredicatePolicy is an autogenerated conversion function.
func Convert_policy_PredicatePolicy_To_v1alpha1_PredicatePolicy(in *policy.PredicatePolicy, out *PredicatePolicy, s conversion.Scope) error {
	return autoConvert_policy_PredicatePolicy_To_v1alpha1_PredicatePolicy(in, out, s)
}

func autoConvert_v1alpha1_PriorityPolicy_To_policy_PriorityPolicy(in *PriorityPolicy, out *policy.PriorityPolicy, s conversion.Scope) error {
	out.Name = in.Name
	out.Weight = in.Weight
	return nil
}

// Convert_v1alpha1_PriorityPolicy_To_policy_PriorityPolicy is an autogenerated conversion function.
func Convert_v1alpha1_PriorityPolicy_To_policy_PriorityPolicy(in *PriorityPolicy, out *policy.PriorityPolicy, s conversion.Scope) error {
	return autoConvert_v1alpha1_PriorityPolicy_To_policy_PriorityPolicy(in, out, s)
}

func autoConvert_policy_PriorityPolicy_To_v1alpha1_PriorityPolicy(in *policy.PriorityPolicy, out *PriorityPolicy, s conversion.Scope) error {
	out.Name = in.Name
	out.Weight = in.Weight
	return nil
}

// Convert_policy_PriorityPolicy_To_v1alpha1_PriorityPolicy is an autogenerated conversion function.
func Convert_policy_PriorityPolicy_To_v1alpha1_PriorityPolicy(in *policy.PriorityPolicy, out *PriorityPolicy, s conversion.Scope) error {
	return autoConvert_policy_PriorityPolicy_To_v1alpha1_PriorityPolicy(in, out, s)
}

func autoConvert_v1alpha1_SyncPolicy_To_policy_SyncPolicy(in *SyncPolicy, out *policy.SyncPolicy, s conversion.Scope) error {
	out.Name = in.Name
	out.Period = in.Period
	return nil
}

// Convert_v1alpha1_SyncPolicy_To_policy_SyncPolicy is an autogenerated conversion function.
func Convert_v1alpha1_SyncPolicy_To_policy_SyncPolicy(in *SyncPolicy, out *policy.SyncPolicy, s conversion.Scope) error {
	return autoConvert_v1alpha1_SyncPolicy_To_policy_SyncPolicy(in, out, s)
}

func autoConvert_policy_SyncPolicy_To_v1alpha1_SyncPolicy(in *policy.SyncPolicy, out *SyncPolicy, s conversion.Scope) error {
	out.Name = in.Name
	out.Period = in.Period
	return nil
}

// Convert_policy_SyncPolicy_To_v1alpha1_SyncPolicy is an autogenerated conversion function.
func Convert_policy_SyncPolicy_To_v1alpha1_SyncPolicy(in *policy.SyncPolicy, out *SyncPolicy, s conversion.Scope) error {
	return autoConvert_policy_SyncPolicy_To_v1alpha1_SyncPolicy(in, out, s)
}
