//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta3

import (
	config "github.com/gocrane/crane-scheduler/pkg/plugins/apis/config"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*DynamicArgs)(nil), (*config.DynamicArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta3_DynamicArgs_To_config_DynamicArgs(a.(*DynamicArgs), b.(*config.DynamicArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DynamicArgs)(nil), (*DynamicArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DynamicArgs_To_v1beta3_DynamicArgs(a.(*config.DynamicArgs), b.(*DynamicArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta3_DynamicArgs_To_config_DynamicArgs(in *DynamicArgs, out *config.DynamicArgs, s conversion.Scope) error {
	if err := v1.Convert_Pointer_string_To_string(&in.PolicyConfigPath, &out.PolicyConfigPath, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta3_DynamicArgs_To_config_DynamicArgs is an autogenerated conversion function.
func Convert_v1beta3_DynamicArgs_To_config_DynamicArgs(in *DynamicArgs, out *config.DynamicArgs, s conversion.Scope) error {
	return autoConvert_v1beta3_DynamicArgs_To_config_DynamicArgs(in, out, s)
}

func autoConvert_config_DynamicArgs_To_v1beta3_DynamicArgs(in *config.DynamicArgs, out *DynamicArgs, s conversion.Scope) error {
	if err := v1.Convert_string_To_Pointer_string(&in.PolicyConfigPath, &out.PolicyConfigPath, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_DynamicArgs_To_v1beta3_DynamicArgs is an autogenerated conversion function.
func Convert_config_DynamicArgs_To_v1beta3_DynamicArgs(in *config.DynamicArgs, out *DynamicArgs, s conversion.Scope) error {
	return autoConvert_config_DynamicArgs_To_v1beta3_DynamicArgs(in, out, s)
}
