//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnotatorConfiguration) DeepCopyInto(out *AnnotatorConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ClientConnection = in.ClientConnection
	in.LeaderElection.DeepCopyInto(&out.LeaderElection)
	in.Debugging.DeepCopyInto(&out.Debugging)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnotatorConfiguration.
func (in *AnnotatorConfiguration) DeepCopy() *AnnotatorConfiguration {
	if in == nil {
		return nil
	}
	out := new(AnnotatorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnnotatorConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
