//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&AnnotatorConfiguration{}, func(obj interface{}) { SetObjectDefaults_AnnotatorConfiguration(obj.(*AnnotatorConfiguration)) })
	return nil
}

func SetObjectDefaults_AnnotatorConfiguration(in *AnnotatorConfiguration) {
	SetDefaults_AnnotatorConfiguration(in)
}
